<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="4" total="5" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="24681" started-at="2017-12-27T18:43:54Z" finished-at="2017-12-27T18:44:19Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="24681" started-at="2017-12-27T18:43:54Z" finished-at="2017-12-27T18:44:19Z">
      <class name="by.http.tstng.tstng_study.BookingComTest">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:by.http.tstng.tstng_study.BookingComTest@5419f379]" name="beforeMethod" is-config="true" duration-ms="7138" started-at="2017-12-27T21:43:54Z" description="Init browser" finished-at="2017-12-27T21:44:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="testErrorMessagePlace()[pri:0, instance:by.http.tstng.tstng_study.BookingComTest@5419f379]" name="testErrorMessagePlace" duration-ms="17365" started-at="2017-12-27T21:44:01Z" finished-at="2017-12-27T21:44:19Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at by.http.tstng.tstng_study.BookingComTest.testErrorMessagePlace(BookingComTest.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testErrorMessagePlace -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:by.http.tstng.tstng_study.BookingComTest@5419f379]" name="afterMethod" is-config="true" duration-ms="152" started-at="2017-12-27T21:44:19Z" finished-at="2017-12-27T21:44:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- by.http.tstng.tstng_study.BookingComTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
